lang: nl
remote_theme: chrisrhymes/bulma-clean-theme
title: Fury_106
google_analytics: UA-191715723-1
footer_menu: footer
favicon: img/favicon.png
url: "https://fury106.github.io"
timezone: 'Europe-Andorra'
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num"
future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:title/
      author: "Fury_106"
      show_sidebar: true
  - 
    scope:
  
      path: ""
      type: "pages"
    values:
      show_sidebar: true
