remote_theme: chrisrhymes/bulma-clean-theme
title: Fury_106
google_analytics: UA-191715723-1
footer_menu: footer
favicon: img/favicon.png
url: "https://fury106.github.io"
timezone: 'Europe-Andorra'

paginate: 5
paginate_path: "/blog/page:num"
future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed